[pytest]
asyncio_mode = auto
pythonpath = .
testpaths = tests app
asyncio_default_fixture_loop_scope = function
addopts = --cov=app --cov-report=term-missing --cov-fail-under=70 --cov-config=pytest.ini

[coverage:run]
omit =
    *test_*.py
    *conftest.py
