import { defineStore } from 'pinia'
import { ref } from 'vue'
import type { Locale, TranslationKey } from '../types'

type TranslationDict = Record<TranslationKey, string>

const translations: Record<Locale, TranslationDict> = {
  en: {
    search_placeholder: "Search tags... (e.g. cat_ears 1girl)",
    search_btn: "Search",
    split_search: "Split Search",
    collapse: "Collapse",
    advanced_search: "Advanced Search",
    mixing_ratio: "Mixing ratio of different sources in the feed",
    no_more_posts: "No more posts ✨",
    no_results: "No results found",
    try_changing: "Try changing tags or selecting different sources",
    failed_load: "Failed to load feed",
    nav_feed: "Feed",
    nav_guides: "Guides",
    nav_favorites: "Favorites",
    nav_bookmarks: "Bookmarks",
    nav_settings: "Settings",
    logout: "Logout",
    login: "Login",
    logged_out: "Logged out successfully",
    added_fav: "Added to favorites",
    removed_fav: "Removed from favorites",
    login_to_fav: "Log in to add to favorites",
    tags_for: "Tags for",
    bookmarks_title: "Bookmarks",
    bookmarks_subtitle: "Saved search queries",
    no_bookmarks: "No bookmarks",
    save_bookmarks_hint: "Save search queries from the search page",
    error_load_bookmarks: "Error loading bookmarks",
    enter_tags_to_save: "Please enter tags to save",
    bookmark_added_msg: "Search query saved to bookmarks",
    favorites_title: "Favorites",
    favorites_subtitle: "Your favorite posts",
    dislikes_title: "Dislikes",
    dislikes_subtitle: "Hidden from feed",
    likes_tab: "Likes",
    dislikes_tab: "Dislikes",
    no_favorites: "No favorites",
    empty_list: "List is empty",
    add_favorites_hint: "Add posts to favorites to see them here",
    error_load_favorites: "Error loading favorites",
    settings_title: "Settings",
    settings_subtitle: "Manage account and filters",
    profile: "Profile",
    start_tags: "Start Tags",
    save_settings: "Save Settings",
    settings_saved: "Settings saved successfully",
    api_keys_section: "API Keys (Encrypted)",
    search_params: "Search Parameters",
    posts_limit: "Posts per page",
    search_interval: "Interval (sec)",
    keys_not_set: "Keys not set",
    keys_configured: "Configured: ",
    api_error: "API error",
    manual_mappings: "Manual Tag Mappings",
    add_mapping: "Add Mapping",
    update_mapping: "Update Mapping",
    mapping_saved: "Mapping saved",
    mapping_created: "Mapping created",
    mapping_deleted: "Mapping deleted",
    blacklist_title: "Blacklist",
    add_rule: "Add Rule",
    rule_added: "Rule added",
    rule_deleted: "Rule deleted",
    welcome: "Welcome back",
    login_subtitle: "Sign in to BooruHub",
    username_email: "Username or email",
    password: "Password",
    signing_in: "Signing in...",
    no_account: "No account?",
    create_account: "Create",
    fill_fields: "Please fill all fields",
    logged_in_msg: "Welcome!",
    create_title: "Create Account",
    already_have: "Have an account?",
    register_btn: "Register",
    registering: "Registering...",
    post_not_found: "Post not found",
    back_to_feed: "Back to Feed",
    remove_from_fav: "Remove from favorites",
    add_to_fav: "Add to favorites",
    original: "Original",
    source: "Source",
    post_id: "Post ID",
    rating: "Rating",
    score: "Score",
    size: "Size",
    format: "Format",
    tags_count: "Tags",
    error_load_post: "Error loading post",
    guides_title: "Guides & Manual",
    guides_subtitle: "Everything you need to know for effective search and BooruHub configuration",
    tab_tags: "Tags",
    tab_api: "API Accounts",
    tab_blacklist: "Blacklist",
    tab_mapping: "Mapping",
    error: "Error",
    loading: "Loading...",
    back: "Back",
    delete: "Delete",
    confirm_delete: "Are you sure you want to delete this?",
    save: "Save",
    did_you_mean: "Did you mean",
  },
  ru: {
    search_placeholder: "Поиск по тегам... (напр. cat_ears 1girl)",
    search_btn: "Поиск",
    split_search: "Раздельный",
    collapse: "Свернуть",
    advanced_search: "Расширенный поиск",
    mixing_ratio: "Соотношение постов из разных источников в ленте",
    no_more_posts: "Постов больше нет ✨",
    no_results: "Ничего не найдено",
    try_changing: "Попробуйте изменить теги или выбрать другие источники",
    failed_load: "Ошибка загрузки ленты",
    nav_feed: "Лента",
    nav_guides: "Гайды",
    nav_favorites: "Избранное",
    nav_bookmarks: "Закладки",
    nav_settings: "Настройки",
    logout: "Выйти",
    login: "Войти",
    logged_out: "Вы вышли из аккаунта",
    added_fav: "Добавлено в избранное",
    removed_fav: "Удалено из избранного",
    login_to_fav: "Войдите, чтобы добавить в избранное",
    tags_for: "Теги для",
    bookmarks_title: "Закладки",
    bookmarks_subtitle: "Сохраненные поисковые запросы",
    no_bookmarks: "Нет закладок",
    save_bookmarks_hint: "Сохраняйте поисковые запросы из страницы поиска",
    error_load_bookmarks: "Ошибка загрузки закладок",
    enter_tags_to_save: "Введите теги для сохранения",
    bookmark_added_msg: "Запрос сохранён в закладки",
    favorites_title: "Избранное",
    favorites_subtitle: "Ваши любимые посты",
    dislikes_title: "Дизлайки",
    dislikes_subtitle: "Скрыты из ленты",
    likes_tab: "Лайки",
    dislikes_tab: "Дизлайки",
    no_favorites: "Нет избранного",
    empty_list: "Список пуст",
    add_favorites_hint: "Добавляйте посты в избранное, чтобы увидеть их здесь",
    error_load_favorites: "Ошибка загрузки списков",
    settings_title: "Настройки",
    settings_subtitle: "Управление аккаунтом и фильтрами",
    profile: "Профиль",
    start_tags: "Стартовые теги",
    save_settings: "Сохранить настройки",
    settings_saved: "Настройки сохранены",
    api_keys_section: "API Ключи (Зашифровано)",
    search_params: "Параметры поиска",
    posts_limit: "Постов за раз",
    search_interval: "Интервал (сек)",
    keys_not_set: "Ключи не установлены",
    keys_configured: "Ключи: ",
    api_error: "Ошибка API",
    manual_mappings: "Ручные маппинги тегов",
    add_mapping: "Добавить маппинг",
    update_mapping: "Обновить маппинг",
    mapping_saved: "Маппинг сохранён",
    mapping_created: "Маппинг создан",
    mapping_deleted: "Маппинг удален",
    blacklist_title: "Блеклист",
    add_rule: "Добавить правило",
    rule_added: "Правило добавлено",
    rule_deleted: "Правило удалено",
    welcome: "Добро пожаловать",
    login_subtitle: "Войдите в BooruHub",
    username_email: "Логин или email",
    password: "Пароль",
    signing_in: "Входим...",
    no_account: "Нет аккаунта?",
    create_account: "Создать",
    fill_fields: "Заполните все поля",
    logged_in_msg: "Вы вошли!",
    create_title: "Регистрация",
    already_have: "Есть аккаунт?",
    register_btn: "Зарегистрироваться",
    registering: "Регистрируем...",
    post_not_found: "Пост не найден",
    back_to_feed: "Вернуться в ленту",
    remove_from_fav: "Убрать из избранного",
    add_to_fav: "В избранное",
    original: "Оригинал",
    source: "Источник",
    post_id: "ID Поста",
    rating: "Рейтинг",
    score: "Оценка",
    size: "Размер",
    format: "Формат",
    tags_count: "Теги",
    error_load_post: "Ошибка загрузки поста",
    guides_title: "Гайды и руководство",
    guides_subtitle: "Всё, что нужно знать для эффективного поиска и настройки BooruHub",
    tab_tags: "Теги",
    tab_api: "API Аккаунты",
    tab_blacklist: "Blacklist",
    tab_mapping: "Маппинг",
    error: "Ошибка",
    loading: "Загрузка...",
    back: "Назад",
    delete: "Удалить",
    confirm_delete: "Вы уверены, что хотите это удалить?",
    save: "Сохранить",
    did_you_mean: "Возможно, вы имели в виду",
  },
}

export const useLangStore = defineStore('lang', () => {
  const locale = ref<Locale>((localStorage.getItem('booruhub_lang') as Locale) || 'en')

  function setLocale(l: Locale) {
    locale.value = l
    localStorage.setItem('booruhub_lang', l)
  }

  function t(key: TranslationKey): string {
    const translation = translations[locale.value][key]
    if (!translation) return translations['en'][key] || key
    return translation
  }

  return { locale, setLocale, t }
})
